[package]
name = "zero-malloc"
description = "Zeroing memory allocation library that intercepts the system malloc()&friends"
version = "0.9.0"
authors = ["The C2Rust Project Developers <c2rust@immunant.com>"]
license = "BSD-3-Clause"
homepage = "https://c2rust.com/"
repository = "https://github.com/immunant/c2rust"
readme = "README.md"

[lib]
crate-type = ["dylib"]

[features]
debug-print = []

[dependencies]
parking_lot = {version = "0.6", features = ["nightly"]}
spin = "0.5.2"

